site_name: UK Gift Aid
repo_url: https://github.com/mattwire/uk.co.compucorp.civicrm.giftaid
theme:
  name: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

nav:
- Release Notes: release/release_notes.md
- Introduction: index.md
- Setup and Configuration: setup.md
- The Gift Aid Declaration: declaration.md
- Contributions and Eligibility: contributions.md
- Creating and managing your batch: batches.md
- Submitting to HMRC / Reporting: submission.md
- Managing the basic rate of Tax: tax.md
- API Functions: api.md

